import React, { useEffect, useRef, useState } from 'react'

import { chapters, questions } from './challengeContent'

const assets = import.meta.glob('./assets/nakayama/*', { eager: true, query: '?url', import: 'default' }) as Record<string,string>
const photo = (name: string) => assets[`./assets/nakayama/${name}`]
const nav = [['challenge','NAKAYAMAの挑戦'],['time','NAKAYAMAでの時間'],['people','私たちについて'],['journal','季節の便り'],['projects','プロジェクト'],['course','コース'],['visit','ご来店案内'],['reserve','ご予約']]
const href = (key: string) => `#/${key}`
function Link({to,children}:{to:string,children:React.ReactNode}) {return <a className={`text-link${to==='course'||to==='reserve'?' text-link-primary':''}`} href={href(to)}>{children}</a>}
function Photo({name,alt,portrait=false}:{name:string,alt:string,portrait?:boolean}) {return <img className={portrait?'portrait':''} src={photo(name)} alt={alt} loading="lazy"/>}
function Scene({image,kicker,title,children,portrait=false}:{image:string,kicker:string,title:string,children:React.ReactNode,portrait?:boolean}) {
 return <section className={'scene'+(portrait?' portrait-scene':'')}><div className="scene-stage"><Photo name={image} alt={title} portrait={portrait}/><div className="shade"/><div className="scene-copy"><span className="eyebrow">{kicker}</span><h2>{title}</h2><div>{children}</div></div><span className="scene-line" aria-hidden="true"/></div></section>
}
function Intro({title,en,children}:{title:string,en:string,children?:React.ReactNode}) {return <section className="page-intro"><span className="eyebrow">{en}</span><h1>{title}</h1>{children&&<p>{children}</p>}</section>}
function Home(){return <><section className="opening"><div className="opening-stage"><Photo name="miyota-forest.jpg" alt="西軽井沢の森に差し込む光"/><div className="opening-wash"/><img className="opening-logo" src={photo('brand.svg')} alt="NAKAYAMA da arte a Karuizawa"/><p className="opening-caption">この土地と<br/>その日の出会いを<br/>NAKAYAMAで</p><span className="scroll-cue">SCROLL TO DISCOVER<span>│</span></span></div></section><section className="manifesto"><span className="eyebrow">NAKAYAMA DA ARTE</span><h1>ここまで来てよかった。<br/>そのひと言のために。</h1><p>信州を、北イタリアの感性で料理する。<br/>目の前の食材に向き合い、<br/>その日だけの美味しさを探す。</p><p>そして、ここでしか過ごせない時間をお届けする。<br/>それが私たちの挑戦です。</p><Link to="challenge">NAKAYAMAの挑戦</Link></section><Scene image="hands-hero.jpg" kicker="01 / THE HANDS" title="レシピの先に、その日がある。"><p>同じ食材でも、一つひとつ違う個性。<br/>触れて、見つめて、いちばんの瞬間を待つ。</p><Link to="people">私たちについて</Link></Scene><Scene image="tortellini.jpg" kicker="02 / AT THE TABLE" title="美味しさは、時間の中に。"><p>料理も、器も、会話も。<br/>食卓を囲むひととき、そのすべてを。</p><Link to="time">NAKAYAMAでの時間</Link></Scene><section className="editorial"><span className="eyebrow">LETTERS FROM NAKAYAMA</span><h2>店も、庭も、育っていく。</h2><Cards items={[['journal','miyota-birch.jpg','季節の便り','土地と暮らしの、小さな発見。'],['projects','miyota-site.jpg','プロジェクト','この場所から、はじまること。']]}/></section></>}
function Cards({items}:{items:string[][]}){return <div className="cards">{items.map(([to,img,title,desc])=><a key={to} href={href(to)}><div className="card-image"><Photo name={img} alt={title}/></div><h3>{title}<span>↗</span></h3><p>{desc}</p></a>)}</div>}
function Challenge(){return <><Intro title="NAKAYAMAの挑戦" en="OUR PHILOSOPHY">土地に向き合うこと。目の前の食材に向き合うこと。</Intro><nav className="chapter-index" aria-label="章の目次">{chapters.map((c,i)=><button key={c.title} onClick={()=>document.getElementById('chapter-'+i)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}>{String(i+1).padStart(2,'0')} {c.title}</button>)}</nav>{chapters.map((c,i)=><article className="chapter" id={'chapter-'+i} key={c.title}><div className="chapter-photo"><Photo name={c.image} alt={['浅間山の冬景色','生地の状態を確かめる手','食材を組み合わせた料理','リゾットの仕上がり','西軽井沢の白樺','料理をつくる手'][i]}/><span aria-hidden="true">{String(i+1).padStart(2,'0')} / 06</span></div><div className="chapter-body"><span className="eyebrow">CHAPTER {String(i+1).padStart(2,'0')}</span><h2>{c.title}</h2>{c.paragraphs.map((p,j)=><React.Fragment key={j}><p>{p}</p>{i===1&&j===3&&<aside className="source-note"><p>UNESCOも、イタリア料理を説明する中で、<q lang="en">respect for ingredients</q>（食材への敬意）を挙げています。</p><a href="https://ich.unesco.org/en/RL/italian-cooking-between-sustainability-and-biocultural-diversity-02093" target="_blank" rel="noopener noreferrer">出典：UNESCO「Italian cooking, between sustainability and biocultural diversity」</a></aside>}</React.Fragment>)}{i===3&&<p className="source-note">mantecareの語義参照：<a href="https://www.treccani.it/vocabolario/mantecare/" target="_blank" rel="noopener noreferrer">Treccani</a>。山田錦の詳しい選択理由は中山さんへの確認後に追記します。</p>}{i===5&&<p className="source-note">経歴・器の仕事に関する記述の参照：<a href="https://www7b.biglobe.ne.jp/~arte/" target="_blank" rel="noopener noreferrer">arte現行サイト</a>。</p>}</div></article>)}<section className="reading"><Link to="course">コースについて</Link></section></>}
function Questions(){return <><Intro title="中山さんへの質問" en="EDITORIAL / QUESTIONS">原稿を、ご本人の経験と言葉に近づけるために。</Intro><section className="reading"><p className="draft-note">制作・取材用の質問ページです。回答はまだ掲載していません。まずは山田錦について、ほかの質問は答えやすいものからお聞かせください。</p>{questions.map((q,i)=><section className="question" key={q.title}><span className="eyebrow">QUESTION {String(i+1).padStart(2,'0')}</span><h2>{q.title}</h2><p>{q.text}</p><ul>{q.points.map(p=><li key={p}>{p}</li>)}</ul></section>)}<Link to="challenge">原稿を読む</Link></section></>}
function Time(){return <><Intro title="NAKAYAMAでの時間" en="A MOMENT WITH US">店に向かう道から、食後の余韻まで。</Intro><Scene image="asama-road.jpg" kicker="01 / ON THE WAY" title="食事の前に、深呼吸。"><p>浅間山のふもとへ。<br/>窓の外に移りゆく風景も、この日の楽しみに。</p></Scene><Scene image="miyota-birch.jpg" kicker="02 / APERITIVO" title="まずは、外の空気とともに。"><p>庭で前菜と食前酒を楽しんでから、店内へ。<br/>季節と天候に合わせて、自然を感じるお迎えを考えています。</p><small>屋外での提供方法は検討中です。</small></Scene><Scene image="agnolotti.jpg" kicker="03 / AT THE TABLE" title="選んだ理由が、食卓に集まる。"><p>料理を受け止める器。ゆっくり過ごせる椅子。<br/>一つひとつに、つくる人と、選んだ理由があります。</p></Scene><Scene image="apple-dessert.jpg" kicker="04 / AFTERGLOW" title="帰り道にも、つづく余韻。"><p>美味しかった、だけではない。<br/>また会いに来たくなる時間でありますように。</p><Link to="course">コースを見る</Link></Scene></>}
function People(){return <><Intro title="私たちについて" en="THE PEOPLE">それぞれの経験が、一つの店になる。</Intro><div className="split editorial"><Photo name="chef-tomohide.png" alt="シェフ 中山友秀" portrait/><div><span className="eyebrow">CHEF / TOMOHIDE NAKAYAMA</span><h2>イタリアの15年が、<br/>今日の仕事に。</h2><p>出会った人、食べたもの、教わった手仕事。<br/>土地に根ざしたイタリア料理への想いを、この場所で。</p><Link to="chef">シェフ紹介</Link></div></div><Scene image="pannacotta.jpg" kicker="THE ART OF WELCOMING" title="器を選ぶことも、お迎えすること。"><p>器の仕事に長く携わってきた経験を、食卓と空間へ。<br/>料理との相性と、お客様の心が華やぐ瞬間を大切にしています。</p></Scene><section className="manifesto"><h2>私たち二人だけでは、<br/>つくれない店。</h2><p>生産者、作家、職人、そして一緒に考えてくださる人たち。<br/>それぞれの仕事が、NAKAYAMAをつくっています。</p><Link to="projects">ともにつくるプロジェクト</Link></section></>}
function Chef(){return <><Intro title="中山友秀" en="CHEF / TOMOHIDE NAKAYAMA">経歴の先にある、今の料理のルーツ。</Intro><div className="chef-frame"><Photo name="chef-tomohide.png" alt="中山友秀のポートレート" portrait/></div><Scene image="chef-kitchen.jpg" kicker="ROOTS IN ITALY" title="学んだ感覚を、自分の手で。"><p>2006年に渡伊。ピエモンテ、トスカーナ、ピアチェンツァへ。<br/>15年間の仕事を通じて、その土地の食材と向き合う感覚を育んできました。</p></Scene><section className="reading"><h2>同じ道の、つづきへ。</h2><p>2021年に帰国し、2022年、板橋でarteを開きました。そこで皆さまと過ごした時間も、大切にしてきた手仕事も、新しい店へ持っていきます。</p><p>どこで、誰と出会い、何を学んだのか。具体的な記憶と現在の料理をつなぐお話を、これから紹介していきます。</p><Link to="people">私たちについて</Link></section></>}
const journalItems=[['letter-hands','hand-pasta.jpg','手から生まれる、かたち。','手打ちパスタと、その日の感覚。'],['letter-garden','miyota-forest.jpg','森から、庭へ。','土地とともに育つ店。'],['landscape','bisque-pasta.jpg','風景','写真でめぐるNAKAYAMA。']]
function Journal(){return <><Intro title="季節の便り" en="JOURNAL">料理、土地、人の手。日々の小さな発見を。</Intro><section className="editorial"><p className="draft-note">試作記事です。日付を伴う実際の出来事としての掲載は、取材・確認後に行います。</p><Cards items={journalItems}/></section></>}
function Letter({garden=false}:{garden?:boolean}){return <><Intro title={garden?'森から、庭へ。':'手から生まれる、かたち。'} en="JOURNAL / DRAFT"/><Scene image={garden?'miyota-forest.jpg':'hand-pasta.jpg'} kicker={garden?'LAND & SEASONS':'HANDS & CRAFT'} title={garden?'完成してからも、育っていく。':'同じ仕事を、同じにはしない。'}><p>{garden?'季節が変わり、庭が育ち、人とのつながりが増えていく。その小さな変化を、この場所から伝えていきたいと思います。':'触れて確かめる。目で見て、頃合いを判断する。その日の状態に向き合う手仕事を大切にしています。'}</p></Scene><section className="reading"><p className="draft-note">いただいた想いをもとにした仮の記事です。制作の様子や具体的なエピソードは、今後の記録を追加します。</p><Link to="journal">季節の便りへ</Link></section></>}
function Projects(){return <><Intro title="プロジェクト" en="WORK IN PROGRESS">つくりながら、問い続ける。</Intro><section className="editorial"><Cards items={[["project-miyota","miyota-site.jpg","西軽井沢へ、店をつくる","森だった場所に、食卓が生まれるまで。"],["project-dialogue","project-meeting.jpg","自らを見つめ直し、問い直す","芝浦工業大学とともに。"]]}/></section></>}
function Project({dialogue=false}:{dialogue?:boolean}){return <><Intro title={dialogue?'自らを見つめ直し、問い直す':'西軽井沢へ、店をつくる'} en="PROJECT"/><Scene image={dialogue?'project-meeting.jpg':'miyota-site.jpg'} kicker={dialogue?'WITH SHIBAURA INSTITUTE OF TECHNOLOGY':'A RESTAURANT TAKES ROOT'} title={dialogue?'私たちが、本当に大切にしたいこと。':'何もなかった場所に、想いが集まる。'}><p>{dialogue?'対話を通じて、自分たちの仕事と経験を見つめ直す。なぜ選ぶのか、何を届けたいのか。その問いを、芝浦工業大学の皆さんと一緒に考えています。':'建築、厨房、家具、器、そして庭。たくさんの人の手と仕事によって、一つのレストランがかたちになっていきます。'}</p></Scene><section className="reading"><h2>{dialogue?'答えだけでなく、問いの過程を。':'できあがるまでの時間も、残したい。'}</h2><p>{dialogue?'対話の内容や、そこから生まれた気づきは、公開範囲を確認しながら紹介していきます。':'森だった頃から完成までの記録、つくってくださる人たちへの取材を、これから重ねていきます。'}</p><Link to="projects">プロジェクト一覧</Link></section></>}
function Course(){return <><Intro title="コース" en="AT OUR TABLE">その日、集まった食材とともに。</Intro><section className="reading"><p>季節と食材の状態に合わせて組み立てる、おまかせのコース。今、この場所で出会える美味しさをお楽しみください。</p><dl><dt>コース価格</dt><dd>確認中</dd><dt>税・サービス料</dt><dd>確認中</dd><dt>提供時間・所要時間</dt><dd>確認中</dd><dt>お飲み物</dt><dd>内容・価格は確認中</dd></dl><p className="draft-note">新店舗の内容・価格は未確定です。板橋店の条件は流用していません。</p><Link to="reserve">ご予約について</Link></section><Scene image="risotto.jpg" kicker="SEASONAL TASTES" title="今日だからこその、美味しさを。"><p>写真はこれまでの料理の一例です。<br/>当日の提供内容をお約束するものではありません。</p></Scene></>}
function Visit(){return <><Intro title="ご来店案内" en="YOUR JOURNEY"/><section className="reading"><h2>NAKAYAMAを目的にした旅へ。</h2><p>浅間山のふもと、西軽井沢へ。食事の前後の時間も、ゆっくりお楽しみいただけるよう、旅の案内を整えています。</p><dl>{['住所・地図','営業時間・定休日','駐車場','公共交通・タクシー','周辺の宿'].map(x=><React.Fragment key={x}><dt>{x}</dt><dd>新店舗の情報は確認中です</dd></React.Fragment>)}</dl><h2>旅の寄り道</h2><p>私たちが本当に好きな道や場所を、これからご紹介します。季節や道路状況を確認してご案内します。</p><Link to="reserve">ご予約について</Link></section></>}
function Reserve(){return <><Intro title="ご予約" en="RESERVATIONS">お会いできる時間を、楽しみに。</Intro><section className="reading"><h2>ご予約の前に</h2><p>このページは新店舗サイトの試作です。新店舗の予約受付を行うものではありません。</p><div className="notice"><h3>現行の板橋店の予約先</h3><p>現在のarteの予約ページを、参考としてご覧いただけます。西軽井沢店への予約ではありません。</p><a className="text-link" href="https://res-reserve.com/ja/restaurants/arte" target="_blank" rel="noopener noreferrer">板橋店の予約ページ（外部）<span>↗</span></a></div><p className="draft-note">移転後のサービス継続・予約URLは確認中です。</p>{['アレルギーについて','お子様のご来店','服装について','変更・キャンセルについて'].map(x=><details key={x}><summary>{x}</summary><p>新店舗の対応・条件は確認中です。確定後、相談方法とあわせてご案内します。</p></details>)}<Link to="course">コースを見る</Link></section></>}
function Gallery(){const dialog=useRef<HTMLDialogElement>(null);const [selected,setSelected]=useState('');return <><Intro title="風景" en="A GLIMPSE OF NAKAYAMA">料理も、手元も、土地の表情も。</Intro><section className="gallery">{['tortellini.jpg','hands-work.jpg','miyota-birch.jpg','pannacotta.jpg','touch-dough.jpg','asama-winter.jpg','bisque-pasta.jpg','apple-dessert.jpg'].map((x,i)=><button key={x} onClick={()=>{setSelected(x);dialog.current?.showModal()}} aria-label={`写真${i+1}を拡大`}><Photo name={x} alt={['トルテッリーニ','料理をつくる手','白樺の風景','デザート','生地に触れる手','冬の浅間山','手打ちパスタ','りんごのデザート'][i]}/></button>)}</section><dialog className="lightbox" ref={dialog} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}}><button className="close" autoFocus onClick={()=>dialog.current?.close()}>閉じる ×</button>{selected&&<img src={photo(selected)} alt="拡大した写真"/>}</dialog></>}
function App(){const route=()=>{const key=location.hash.replace('#/','')||'home';return ({cucina:'challenge',experience:'time'} as Record<string,string>)[key]||key};const [page,setPage]=useState(route);const menu=useRef<HTMLDialogElement>(null);useEffect(()=>{const go=()=>{setPage(route());menu.current?.close();window.scrollTo(0,0)};addEventListener('hashchange',go);return()=>removeEventListener('hashchange',go)},[]);useEffect(()=>{document.title=`${nav.find(n=>n[0]===page)?.[1]||'NAKAYAMA'} — 試作`;let frame=0;const update=()=>{frame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;document.documentElement.style.setProperty('--scroll',String(reduced?0:window.scrollY));document.querySelectorAll<HTMLElement>('.scene,.opening').forEach(el=>{const r=el.getBoundingClientRect();const p=Math.max(0,Math.min(1,-r.top/(el.offsetHeight-innerHeight)));el.style.setProperty('--progress',String(reduced?0:p))})};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);update();return()=>{removeEventListener('scroll',scroll);removeEventListener('resize',scroll);cancelAnimationFrame(frame)}},[page]);let content;switch(page){case'home':content=<Home/>;break;case'questions':content=<Questions/>;break;case'challenge':content=<Challenge/>;break;case'time':content=<Time/>;break;case'people':content=<People/>;break;case'chef':content=<Chef/>;break;case'journal':content=<Journal/>;break;case'letter-hands':content=<Letter/>;break;case'letter-garden':content=<Letter garden/>;break;case'projects':content=<Projects/>;break;case'project-miyota':content=<Project/>;break;case'project-dialogue':content=<Project dialogue/>;break;case'course':content=<Course/>;break;case'visit':content=<Visit/>;break;case'reserve':content=<Reserve/>;break;case'landscape':content=<Gallery/>;break;default:content=<><Intro title="ページが見つかりません" en="NOT FOUND"/><Link to="home">ホームへ戻る</Link></>}
return <><a className="skip" href="#content" onClick={e=>{e.preventDefault();document.getElementById('content')?.focus()}}>本文へ</a><header><a href="#/home" aria-label="NAKAYAMA ホーム"><img src={photo('brand.svg')} alt="NAKAYAMA"/></a><div className="header-right"><span className="prototype-label">PREVIEW</span><button onClick={()=>menu.current?.showModal()} aria-label="メニューを開く">MENU <span>☰</span></button></div></header><dialog ref={menu} className="menu" onClick={e=>{if(e.target===e.currentTarget)menu.current?.close()}}><button className="close" autoFocus onClick={()=>menu.current?.close()}>閉じる ×</button><span className="eyebrow">NAKAYAMA</span><nav aria-label="サイトメニュー"><a href="#/home">ホーム</a>{nav.map(([key,label],i)=><a className={i===5?'nav-divider':''} key={key} href={href(key)} aria-current={page===key?'page':undefined}>{label}<span>↗</span></a>)}</nav></dialog><div className="particles" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,top:`${(i*23)%100}%`,animationDelay:`-${i*2}s`}}/>)}</div><main id="content" tabIndex={-1} key={page}>{content}</main><footer><img src={photo('brand.svg')} alt="NAKAYAMA da arte"/><p>信州を、北イタリアの感性で。</p><div><Link to="course">コース</Link><Link to="visit">ご来店案内</Link><Link to="reserve">ご予約</Link></div><p className="editorial-link"><a href="#/questions">制作メモ：中山さんへの質問</a></p><small>試作サイト · 写真には板橋店の料理・移転準備の記録を含みます。<br/>新店舗の価格・所在地・営業条件は確認中です。</small></footer></>}
export default App
