import { useScrollHeader } from './useScrollHeader'
import React, { useEffect, useRef, useState } from 'react'

import { chapters, questions } from './challengeContent'
import ChallengeStory from './ChallengeStory'
import ArteHome from './ArteHome'
import './people-timeline.css'
import './visit-projects.css'
import InstagramJournal, { InstagramPost } from './InstagramJournal'

const assets = import.meta.glob('./assets/nakayama/*', { eager: true, query: '?url', import: 'default' }) as Record<string,string>
const photo = (name: string) => assets[`./assets/nakayama/${name}`]
const nav = [['challenge','arteの心'],['course','arteのメニュー'],['time','arteという体験'],['people','私たちについて'],['karuizawa','西軽井沢という挑戦'],['projects','プロジェクト'],['visit','ご来店・予約']]
const href = (key: string) => `#/${key}`
function Link({to,children}:{to:string,children:React.ReactNode}) {return <a className={`text-link${to==='course'||to==='reserve'?' text-link-primary':''}`} href={href(to)}>{children}</a>}
function Photo({name,alt,portrait=false}:{name:string,alt:string,portrait?:boolean}) {return <img className={portrait?'portrait':''} src={photo(name)} alt={alt} loading="lazy"/>}
function Scene({image,kicker,title,children,portrait=false}:{image:string,kicker:string,title:string,children:React.ReactNode,portrait?:boolean}) {
 return <section className={'scene'+(portrait?' portrait-scene':'')}><div className="scene-stage"><Photo name={image} alt={title} portrait={portrait}/><div className="shade"/><div className="scene-copy"><span className="eyebrow">{kicker}</span><h2>{title}</h2><div>{children}</div></div><span className="scene-line" aria-hidden="true"/></div></section>
}
function Intro({title,en,children}:{title:string,en:string,children?:React.ReactNode}) {return <section className="page-intro"><span className="eyebrow">{en}</span><h1>{title}</h1>{children&&<p>{children}</p>}</section>}
function Home(){return <ArteHome/>}
function NakayamaHome(){return <><Intro title="西軽井沢という挑戦" en="ARTE TO NAKAYAMA">2027年5月、板橋から西軽井沢へ。</Intro><Scene image="karuizawa-site-clearing.jpg" kicker="THE NEXT CHAPTER" title="変わらない心を、新しい土地へ。"><p>食材の個性を見きわめ、美味しさを重ねる。<br/>板橋で大切にしてきた姿勢を、さらに深めるために。</p></Scene><section className="reading"><h2>{chapters[4].title}</h2>{chapters[4].paragraphs.map(p=><p key={p}>{p}</p>)}<h2>信州を、北イタリアの感性で料理する。</h2>{chapters[0].paragraphs.slice(8,9).map(p=><p key={p}>{p}</p>)}</section><Scene image="miyota-birch.jpg" kicker="A NEW EXPERIENCE" title="外の空気を楽しんでから、食卓へ。"><p>まずは外で前菜と食前酒を楽しみ、店内で食事を。<br/>自然を感じながら過ごせる時間を考えています。</p><small>屋外での提供方法は、季節や天候も含めて検討中です。</small></Scene><section className="reading karuizawa-closing"><h2>板橋での時間も、あの看板も。</h2><p>皆さまと重ねた時間を、新しい店へ持っていきます。現在は板橋のarteで営業しています。</p><div className="karuizawa-closing-actions"><Link to="projects">店づくりのプロジェクト</Link><Link to="visit">ご来店・予約</Link></div></section></>}
function Cards({items}:{items:string[][]}){return <div className="cards">{items.map(([to,img,title,desc])=><a key={to} href={href(to)}><div className="card-image"><Photo name={img} alt={title}/></div><h3>{title}<span>↗</span></h3><p>{desc}</p></a>)}</div>}
function Challenge(){return <ChallengeStory />}
function Questions(){return <><Intro title="中山さんへの質問" en="EDITORIAL / QUESTIONS">原稿を、ご本人の経験と言葉に近づけるために。</Intro><section className="reading"><p className="draft-note">制作・取材用の質問ページです。回答はまだ掲載していません。LINEで「01の回答は〜」のように、番号を付けてお返事ください。答えやすい質問からで構いません。番号は今後も変えず、追加の質問は末尾に足していきます。</p>{questions.map((q,i)=><section className="question" key={q.title}><span className="question-number" aria-label={`質問 ${String(i+1).padStart(2,'0')}`}>{String(i+1).padStart(2,'0')}</span><h2>{q.title}</h2><p>{q.text}</p><ul>{q.points.map(p=><li key={p}>{p}</li>)}</ul></section>)}<Link to="challenge">原稿を読む</Link></section></>}
function Time(){return <article className="experience-letter" aria-labelledby="experience-title">
  <div className="experience-letter-heading"><h1 id="experience-title">arteという体験</h1></div>
  <div className="experience-letter-body">
    <p className="experience-salutation">arteで過ごしてくださる皆さまへ</p>
    <p>arteにご興味を持ってくださり、誠にありがとうございます。</p>
    <p>私たちは日々、お客様をお迎えしながら、食事を通じて何をお届けできるのかを考えています。</p>
    <p>美味しい料理を楽しんでいただくことは、もちろんです。それとともに、新しい味や器との出会い、気兼ねなく過ごせる穏やかなひととき、あとから思い出してうれしくなるような記憶。ここで過ごす時間が、皆さまの日々を少し豊かにするものであってほしいと思っています。</p>
    <p>そのために、料理だけでなく、それを彩る器や、落ち着いて過ごしていただくための雰囲気づくりにも気を配っています。どうすれば、もっと楽しんでいただけるだろう。もっと心地よく過ごしていただけるだろう。迷うこともありますが、二人で考え、試しながら、日々工夫を重ねています。</p>
    <p>お腹が満たされるだけでなく、気持ちにも少し余裕ができる。「来てよかった」と思えて、その日の午後や、次の日が少し楽しみになる。</p>
    <p>arteで過ごしてくださる皆さまに、そんなひとときをお届けしたいと思っています。</p>
    <p>どうぞ、穏やかで特別なひとときをお愉しみください。</p>
    <p className="experience-signature">arte</p>
  </div>
</article>}
function People(){
 const album=(items:[string,string][]) => <div className="people-album">{items.map(([name,caption])=><figure key={name}><Photo name={name} alt={caption}/><figcaption>{caption}</figcaption></figure>)}</div>
 return <div className="people-page"><Intro title="私たちについて" en="OUR STORY">料理をつくること。食事の時間をつくること。</Intro>
 <section className="people-profile"><Photo name="chef-tomohide.png" alt="シェフ 中山友秀" portrait/><div><span className="eyebrow">CHEF</span><h2>中山友秀</h2><p>イタリアで料理に向き合った15年。帰国後、板橋で夫婦二人のレストラン、arteを開きました。</p><p>料理を担うシェフと、器の仕事に20年以上携わってきた妻。それぞれの経験を、皆さまをお迎えする日々につなげています。</p></div></section>
 <div className="people-timeline">
 <section className="people-milestone"><div className="people-year"><span>2000</span><p>卒業、東京での修業</p></div><div className="people-history"><h2>料理人としての歩みを、東京から。</h2><p>2000年、服部栄養専門学校 調理師本科（昼1年）を卒業。東京・広尾「アッカ」などで修業を重ねたのち、2006年にイタリアへ渡りました。</p></div></section>
 <section className="people-milestone"><div className="people-year"><span>2006</span><p>イタリアへ</p></div><div className="people-history"><h2>土地と人に出会い、料理を学ぶ。</h2><p>2006年に渡伊。ピエモンテ、トスカーナ、そしてピアチェンツァへ。厨房で学ぶ技術と、その土地で暮らしながら触れる食文化。イタリアでの日々が、今の料理の土台になっています。</p><p>最初の約6年間は、ピエモンテでの経験を中心に。いただいた写真には、街の風景や食材の売場、仲間と過ごした時間も残っています。</p>{album([['people-1790047970743.jpg','イタリア滞在中、仲間との一枚'],['people-1790047971638.jpg','滞在中に残した街の風景'],['people-1790047982035.jpg','食材が並ぶ売場の記録']])}</div></section>
 <section className="people-milestone"><div className="people-year"><span>ITALIA</span><p>ピアチェンツァでの9年</p></div><div className="people-history"><h2>現地の厨房を任されて。</h2><p>エミリア＝ロマーニャ州のピアチェンツァで、9年間シェフとして料理をつくり続けました。乾麺、詰め物、手打ちパスタ。その土地で培った技術とパスタ文化は、arteの料理の大きな軸になっています。</p>{album([['people-1790047993314.jpg','ピアチェンツァ時代の厨房'],['people-1790047993286.jpg','ピアチェンツァ時代、人と過ごした時間']])}</div></section>
 <section className="people-milestone"><div className="people-year"><span>2021</span><p>15年を経て、帰国</p></div><div className="people-history"><h2>料理とともに残る、人とのつながり。</h2><p>イタリアで出会った恩師たち。ラ・チャウ・デル・トルナヴェントのシェフ、そしてイル・ペリカーノ時代からの恩師アントニオ・グイダ氏。15年間の仕事を支え、今の料理につながる出会いです。</p>{album([['people-1790048011311.jpg','帰国間際、ラ・チャウ・デル・トルナヴェントの恩師と'],['people-1790048011340.jpg','イル・ペリカーノ時代からの恩師、アントニオ・グイダ氏と（撮影年未確認）']])}</div></section>
 <section className="people-milestone"><div className="people-year"><span>2022</span><p>板橋 arteを開く</p></div><div className="people-history"><h2>二人の経験が、一つの店に。</h2><p>イタリアから持ち帰った料理の経験と、長く器に携わってきた経験。板橋のarteで、それぞれの仕事が一つになりました。シェフは料理を、妻は器やサービス、空間を。夫婦二人で皆さまをお迎えしています。</p><div className="people-turning-point"><span className="eyebrow">ARTEでの変化</span><h3>料理の技術から、<br/>食事の体験全体へ。</h3><p>arteを開いてから、料理の技術を磨くことに加え、お客様にどんな時間を過ごしていただくかへと、意識が広がってきました。料理だけでなく、器やおもてなしを含めた体験を考える。その変化について、これからお二人の言葉を伺っていきます。</p></div><InstagramPost id="DcpMRiESUXj" title="考えて、書いて、昔のレシピをひらいて。"/><Link to="time">arteという体験</Link></div></section>
 <section className="people-milestone"><div className="people-year"><span>2026</span><p>器と、作り手のこと</p></div><div className="people-history"><h2>料理に寄り添う、<br/>器と作り手の仕事。</h2><p>高知で作家の工房を訪ねたとき、妻はあらためて「やっぱり器の仕事が好きなんだ」と感じました。20年以上携わってきた器。その向こう側にいる作り手の手仕事も、料理を通じてお客様に知っていただけたらと考えています。</p><p>シェフがイタリアで積み重ねた15年と、その料理がarteの主軸であることは変わりません。そこに寄り添う器や作り手との出会いが、お客様の知らなかった世界を、ほんの少し広げるきっかけになれたら。そのお手伝いもしていきたいと思っています。</p></div></section>
 <section className="people-milestone"><div className="people-year"><span>2027.05</span><p>西軽井沢へ・移転予定</p></div><div className="people-history"><h2>板橋で育った心を、次の土地へ。</h2><p>新しい水や食材、人との出会いの中で、料理と食事の時間をさらに深めていく。板橋で皆さまと過ごした時間を携えて、西軽井沢のNAKAYAMAへと歩みを進めます。</p><Link to="karuizawa">西軽井沢という挑戦</Link></div></section>
 </div></div>
}
function Chef(){return <People/>}
const journalItems=[['letter-hands','hand-pasta.jpg','手から生まれる、かたち。','手打ちパスタと、その日の感覚。'],['letter-garden','miyota-forest.jpg','森から、庭へ。','土地とともに育つ店。'],['landscape','bisque-pasta.jpg','風景','写真でめぐるNAKAYAMA。']]
function Journal(){return <><Intro title="季節の便り" en="JOURNAL">料理、土地、人の手。日々の小さな発見を。</Intro><section className="editorial"><p className="draft-note">試作記事です。日付を伴う実際の出来事としての掲載は、取材・確認後に行います。</p><Cards items={journalItems}/></section></>}
function Letter({garden=false}:{garden?:boolean}){return <><Intro title={garden?'森から、庭へ。':'手から生まれる、かたち。'} en="JOURNAL / DRAFT"/><Scene image={garden?'miyota-forest.jpg':'hand-pasta.jpg'} kicker={garden?'LAND & SEASONS':'HANDS & CRAFT'} title={garden?'完成してからも、育っていく。':'同じ仕事を、同じにはしない。'}><p>{garden?'季節が変わり、庭が育ち、人とのつながりが増えていく。その小さな変化を、この場所から伝えていきたいと思います。':'触れて確かめる。目で見て、頃合いを判断する。その日の状態に向き合う手仕事を大切にしています。'}</p></Scene><section className="reading"><p className="draft-note">いただいた想いをもとにした仮の記事です。制作の様子や具体的なエピソードは、今後の記録を追加します。</p><Link to="journal">季節の便りへ</Link></section></>}
function Projects(){return <><Intro title="プロジェクト" en="WORK IN PROGRESS">西軽井沢の新しい店を、どうつくり、どう伝えていくか。</Intro><section className="projects-overview"><div className="projects-lead"><p>板橋のarteで積み重ねてきた料理と、お客様をお迎えする仕事。その中で大切にしてきたことを見つめ直しながら、西軽井沢の店づくりを進めています。</p><p>ここでは、現地の変化や作り手との出会いをたどる記録と、芝浦工業大学の研究室と一緒に、店のあり方や伝え方を考える取り組みをご紹介します。</p></div><article className="project-overview-item"><Photo name="karuizawa-site-clearing.jpg" alt="西軽井沢の新店舗予定地"/><div><span className="eyebrow">01 / 店づくりの記録</span><h2>西軽井沢へ、店をつくる</h2><p>伐採前の森から、敷地の整備、建築へ。現地の変化を写真とともに記録しています。生産者を訪ねること、料理に合わせる器を作り手と考えることも、新しい店をつくる大切な仕事です。</p><p>Instagramでお伝えしている日々の出来事と、お寄せいただいた写真を、時系列でたどれるようにまとめています。</p><Link to="project-miyota">店づくりの記録を見る</Link></div></article><article className="project-overview-item"><Photo name="project-meeting.jpg" alt="芝浦工業大学の研究室との打ち合わせ"/><div><span className="eyebrow">02 / 研究室との取り組み</span><h2>これまでを見つめ直し、<br/>これからの店を考える</h2><p>自分たちは何をしてきたのか、何を大切にし、何を目指しているのか。芝浦工業大学デザイン工学部 動態デザイン研究室の教授・学生たちと、対話や現地視察を重ねながら、あらためて考えています。</p><p>その思いを、西軽井沢の店や、お客様への伝え方にどう反映するか。ロゴと、このウェブサイトも、店全体のあり方を考える取り組みの中から生まれています。</p><Link to="project-dialogue">対話と制作の過程を見る</Link></div></article></section></>}
function Project({dialogue=false}:{dialogue?:boolean}){return <><Intro title={dialogue?'自らを見つめ直し、問い直す':'西軽井沢へ、店をつくる'} en="PROJECT"/><Scene image={dialogue?'project-meeting.jpg':'miyota-site.jpg'} kicker={dialogue?'WITH SHIBAURA INSTITUTE OF TECHNOLOGY':'A RESTAURANT TAKES ROOT'} title={dialogue?'私たちが、本当に大切にしたいこと。':'何もなかった場所に、想いが集まる。'}><p>{dialogue?'これまでの歩みを見つめ直し、これからの店を考える。芝浦工業大学デザイン工学部 動態デザイン研究室の教授・学生たちと、二人三脚で取り組んでいます。':'建築、厨房、家具、器、そして庭。たくさんの人の手と仕事によって、一つのレストランがかたちになっていきます。'}</p></Scene>{dialogue?<section className="dialogue-record"><span className="eyebrow">WITH SHIBAURA INSTITUTE OF TECHNOLOGY</span><h2>これまでを見つめ直し、<br/>これからの店を、一緒に考える。</h2><div className="dialogue-overview"><p>私たちはこれまで、何をしてきたのか。どんなことを考え、何を目指して、何に挑戦しているのか。</p><p>西軽井沢での新しい店づくりを機に、自分たちの歩みや思いを、もう一度見つめ直しています。一緒に取り組んでいるのは、芝浦工業大学デザイン工学部 動態デザイン研究室の教授と学生たちです。</p><p>話を重ねながら、当たり前に続けてきた仕事や、大切にしてきたことを言葉にする。そのうえで、新しい店をどうつくり、どのような体験として組み立て、どうお客様に伝えていくかを考えています。</p><p>ロゴやウェブサイトの見た目を整えるだけではありません。店のあり方から伝え方までを一緒に捉え直す、二人三脚の取り組みです。</p></div><h2>言葉を交わし、かたちを探す。</h2><p>打ち合わせでは、考え方を共有し、具体的な案を広げながら検討しています。写真は、ロゴ案を見比べている場面です。</p><div className="dialogue-photos"><figure><Photo name="dialogue-1.jpg" alt="テーブルに並べたNAKAYAMAのロゴ案"/><figcaption>さまざまな案を並べて検討する。</figcaption></figure><figure><Photo name="dialogue-24.jpg" alt="ロゴ案について話し合う打ち合わせの様子"/><figcaption>案を前に、言葉を交わす。</figcaption></figure><figure><Photo name="dialogue-12.jpg" alt="文字やシンボルの組み合わせを比較したロゴ提案資料"/><figcaption>文字とシンボルの組み合わせを見比べる。</figcaption></figure></div><h2>同じ場所に立って、考える。</h2><p>研究室の皆さんと、西軽井沢の現地へ。新しい店ができる場所を一緒に訪ね、店づくりを考える時間を共有しました。</p><div className="dialogue-site-photos"><figure><Photo name="dialogue-site-1.jpg" alt="新店舗の敷地を一緒に視察する様子"/></figure><figure><Photo name="dialogue-site-2.jpg" alt="現地で周囲を見渡しながら話し合う様子"/></figure></div><h2>現時点の成果物</h2><p>NAKAYAMAとarte、2種類のロゴ。そして、ご覧いただいているこのウェブサイトも、研究室との取り組みの一環です。私たちが大切にしていることを、言葉や写真、ページの構成を通じてどう伝えるか。一緒に考えながら、かたちにしています。</p><div className="dialogue-logo-pair"><figure><Photo name="dialogue-logo-nakayama.svg" alt="NAKAYAMA da arte a Karuizawaのロゴ"/></figure><figure><Photo name="dialogue-logo-arte.svg" alt="arteのロゴ"/></figure></div></section>:<InstagramJournal/>}<section className="project-return"><Link to="projects">プロジェクト一覧</Link></section></>}
const arteCourses = [
 {name:'おまかせ定番コース',sub:'La via dell arte — アルテの道',time:'ディナー',price:'15,000',count:'全9品前後',description:'arteを初めて訪れる方にもおすすめの定番コース。冷前菜と温前菜、2皿の手打ちパスタ、メインへと、ひと通りの料理を楽しんでいただけます。',dishes:['小さな料理 2〜3品','冷前菜・温前菜','自家製手打ちパスタ 2皿','メインディッシュ','お口直し・ドルチェ']},
 {name:'お任せライトコース',sub:'La via dell arte — アルテの道',time:'ランチ・ディナー',price:'11,000',count:'全6品前後',description:'定番コースの味わいを、コンパクトに。看板料理のポモドーロと手打ちパスタを中心に、前菜とメインは軽やかな構成でご用意します。',dishes:['小さな料理・前菜','arteのポモドーロ','自家製手打ちパスタ','メインディッシュ・ドルチェ']},
 {name:'特別フルコース',sub:'La via dell arte — アルテの道',time:'ディナー',price:'22,000',count:'全11品前後',description:'魚料理も含めて、arteの料理をより深く味わうフルコース。メインにはフランス産小鳩、または特選和牛をご用意します。',dishes:['小さな料理 3品','冷前菜・温前菜','自家製手打ちパスタ','自家製手打ちパスタ または リゾット','本日の鮮魚','メインディッシュ（小鳩または特選和牛）','お口直し・ドルチェ']},
 {name:'アルテの扉',sub:'La porta dell arte',time:'ランチ限定',price:'5,500',count:'',description:'北イタリアの郷土料理を小皿で楽しんだあとに、自家製手打ちパスタを。夜のarteへとつながる入口として、気軽に楽しんでいただくランチコースです。',dishes:['北イタリアの郷土料理 小皿約5皿','自家製手打ちパスタ','小さなドルチェ・食後のお飲み物'],note:'パスタはポモドーロへ変更可能。メイン料理の追加は予約サイトのオプションをご確認ください。5歳以上のお子様のご予約はお電話で承ります。お子様メニュー・子ども椅子はございません。'},
 {name:'東京arteの集大成',sub:'イタリア料理、その本質へ',time:'ランチ・ディナー',price:'17,800',count:'',description:'移転を前に、板橋での歩みを一つのコースに。乾麺、詰め物、手打ちロング、季節の手打ちという4種のパスタを少量ずつ味わい、日本短角牛のブラザート・アル・バローロへと続きます。',dishes:['北イタリアの郷土料理 5つの小さな料理','チポッラ・リピエーナ','4種のパスタ','岩手県久慈市 日本短角牛のブラザート・アル・バローロ','ドルチェ'],note:'前菜をオマール海老とマルサラ酒のザバイオーネに変更：20,800円。メインを小鳩に変更：20,800円（2名様より）。両方を変更：23,800円（2名様より）。いずれもコース総額・税込です。5歳以上のお子様からご入店いただけます。お子様メニュー・子ども椅子はございません。'},
 {name:'Tre Paste',sub:'3種のパスタを愉しむコース',time:'平日ランチ限定',price:'11,000',count:'',description:'乾麺、詰め物、季節の手打ちパスタ。それぞれの形や食感、ソースの違いを少しずつ楽しむコースです。メイン料理は設けず、3種のパスタを中心に構成しています。',dishes:['北イタリアの郷土料理 2つの小さな料理','チポッラ・リピエーナ','3種のパスタ','ドルチェ・カフェ'],note:'5歳以上のお子様からご入店いただけます。お子様メニュー・子ども椅子はございません。'}
]
function Course(){
 const renderCourse=(index:number)=>{
  const course=arteCourses[index]
  return <article className="menu-choice" key={course.name}>
   <div className="menu-course-label">
    <div className="menu-choice-meta"><span>{course.time}</span>{course.count&&<span>{course.count}</span>}</div>
    <h3>{course.name}</h3>
    <p className="course-subtitle">{course.sub}</p>
    <p className="menu-choice-price">{course.price}<small>円（税込）</small></p>
   </div>
   <div className="menu-course-body">
   <p className="menu-choice-description">{course.description}</p>
   <div className="menu-course-dishes"><h4>料理構成</h4><ul>{course.dishes.map(d=><li key={d}>{d}</li>)}</ul>{course.note&&<p className="course-note">{course.note}</p>}</div>
   <a className="menu-booking" href="https://res-reserve.com/ja/restaurants/arte" target="_blank" rel="noopener noreferrer" aria-label={course.name+'の空席・プランを予約サイトで確認する'}>予約サイトで空席・プランを確認</a>
   </div>
  </article>
 }
 return <div className="menu-guide">
  <Intro title="arteのメニュー" en="LUNCH & DINNER"/>
  <section className="course-introduction course-principles" aria-label="arteの料理の軸">
   <section><h2>料理の軸となる、手仕込みのパスタ</h2><p>シェフ中山友秀の料理の大きな軸のひとつが、パスタです。イタリアで過ごした15年間、そのうち9年間シェフを務めたエミリア＝ロマーニャで培った技術と食文化が、今のarteの料理につながっています。</p><p>自ら仕込む詰め物のパスタや手打ちのロングパスタ、そして乾麺。それぞれの形や食感、合わせるソースによって変わる味わいを大切にしています。コースごとに異なる組み合わせで、パスタの豊かさをお楽しみください。</p></section>
   <section><h2>なめらかな一体感を生む、マンテカーレ</h2><p>パスタやリゾットを、なめらかでまとまりのある状態に仕上げる「マンテカーレ」。arteでは、その仕上がりを生む乳化と、温度の見きわめを大切にしています。</p><p>水分と油分がなじみ、ソースが食材にちょうどよく絡む。口に入れたときに、別々だったものが一体となって感じられる。その状態を見きわめながら、一皿を仕上げていきます。</p></section>
   <section><h2>日本を、北イタリアの感性で料理する。</h2><p>北イタリアで学んだ郷土料理や技術を、日本で出会う食材とともに。目の前にある食材の個性を知り、どうすればその持ち味が活きるのかを考えます。</p><p>例えば「東京arteの集大成」でお出しするブラザート・アル・バローロ。ピエモンテで繰り返し作った料理を、岩手県久慈市の日本短角牛と合わせ、バローロと香味野菜でじっくりと仕立てます。イタリアで身につけた感覚と、日本の食材。その出会いを、arteの料理としてお届けします。</p></section>
   <small>料金はすべてお一人様・税込です。料理内容は季節や仕入れにより変わります。</small>
  </section>
  <section className="menu-family"><div className="menu-section-heading"><h2>レギュラーメニュー</h2></div><div className="menu-choices">{[3,1,0,2].map(renderCourse)}</div></section>
  <section className="menu-family menu-family-special"><div className="menu-section-heading"><h2>スペシャルメニュー</h2><p>西軽井沢への移転を前に、板橋arteで積み重ねてきた料理を、二つのコースに。4種のパスタとメインを味わう「東京arteの集大成」と、パスタに焦点を当てた平日ランチの「Tre Paste」をご用意しています。</p></div><div className="menu-choices">{[4,5].map(renderCourse)}</div></section>
  <section className="course-information"><h2>ご予約にあたって</h2><ul><li>同じグループの皆さまには、同じコースのご注文をお願いしています。</li><li>コースは最大10名様まで。5名様以上はお電話でご相談ください。</li><li>厨房設備の関係上、グルテン・乳製品アレルギーへの対応はいたしかねます。</li><li>当日のキャンセル・人数変更には、お料理分のキャンセル料がかかります。</li><li>定番・ライト・特別フルのディナーは小学生以上。低学年のお子様がコース以外をご希望の場合は、お電話でご相談ください。その他のお子様の条件は各コースと予約サイトでご確認ください。</li></ul><a className="text-link text-link-primary" href="https://res-reserve.com/ja/restaurants/arte" target="_blank" rel="noopener noreferrer">空席・コースを確認して予約する</a><p className="course-source">掲載内容は予約サイトに基づき整理しています（2026年9月22日確認）。最新の内容・条件は予約サイトをご確認ください。</p></section>
 </div>
}
function Visit(){return <><Intro title="ご来店・予約" en="VISIT & RESERVATIONS">板橋 arteのアクセスと営業案内。</Intro><div className="visit-guide">
<section><h2>アクセス</h2><dl className="visit-details"><div><dt>店名</dt><dd>arte（アルテ）<br/>LA CUCINA ITALIANA</dd></div><div><dt>住所</dt><dd>〒173-0004<br/>東京都板橋区板橋3-59-9 1F</dd></div><div><dt>最寄り駅</dt><dd>都営三田線「板橋区役所前駅」より徒歩7分</dd></div><div><dt>電話</dt><dd><a href="tel:0367666416">03-6766-6416</a></dd></div><div><dt>駐車場</dt><dd>専用駐車場はございません。近隣の駐車場をご利用ください。</dd></div></dl><iframe className="visit-map" title="板橋 arteの所在地" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3237.828143021147!2d139.70742619678958!3d35.75502860000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601893b164c13ad1%3A0x50b938bef988881d!2sarte!5e0!3m2!1sja!2sjp!4v1672886489888!5m2!1sja!2sjp" loading="lazy" allowFullScreen referrerPolicy="no-referrer-when-downgrade"/></section>
<section><h2>営業時間・定休日</h2><dl className="visit-details"><div><dt>ランチ</dt><dd><strong>11:00–14:00</strong><br/>ラストオーダー：料理・ドリンク 13:00</dd></div><div><dt>ディナー</dt><dd><strong>17:00–21:00</strong><br/>ラストオーダー：ドリンク 20:00<br/><small>料理の最終受付は確認中です。ご予約の時間にお越しください。</small></dd></div><div><dt>定休日</dt><dd>月曜日・不定休・年末年始</dd></div></dl><p className="visit-note">臨時休業・祝日の営業は変更になる場合があります。個別の日程については、お電話でお問い合わせください。</p></section>
<section><h2>ご予約</h2><p>板橋 arteのご予約は、オンラインで承っています。ご希望のコースをお選びください。</p><a className="text-link text-link-primary" href="https://res-reserve.com/ja/restaurants/arte" target="_blank" rel="noopener noreferrer">板橋 arteを予約する（予約サイト）</a><p>お子様をお連れの場合は、オンラインではなく、お電話でご相談ください。ランチは5歳以上、ディナーは小学生以上のお子様より承ります。</p></section>
<section><h2>ご来店にあたって</h2><dl className="visit-details"><div><dt>お支払い</dt><dd>現金・クレジットカード<br/>VISA / Master / JCB / Amex / Diners<br/>サービス料・チャージ料なし</dd></div><div><dt>アレルギー</dt><dd>厨房設備の都合上、グルテン・乳製品のアレルギーには対応できません。そのほかのアレルギーについても、事前にご相談ください。</dd></div><div><dt>店内について</dt><dd>全席禁煙。ペットの同伴はご遠慮ください。<br/>短パン・かかとのないサンダルでのご来店はご遠慮いただいています。</dd></div><div><dt>お子様の設備</dt><dd>お子様用のメニュー・椅子はございません。</dd></div></dl></section>
<section><h2>西軽井沢への移転について</h2><p>2027年5月の移転を予定しています。板橋店の最終営業日、新店舗の開業日や予約受付は、確定後にご案内します。このページの住所・営業案内・予約先は板橋店のものです。</p><Link to="karuizawa">西軽井沢という挑戦</Link></section></div></>}
function Gallery(){const dialog=useRef<HTMLDialogElement>(null);const [selected,setSelected]=useState('');return <><Intro title="風景" en="A GLIMPSE OF NAKAYAMA">料理も、手元も、土地の表情も。</Intro><section className="gallery">{['tortellini.jpg','hands-work.jpg','miyota-birch.jpg','pannacotta.jpg','touch-dough.jpg','asama-winter.jpg','bisque-pasta.jpg','apple-dessert.jpg'].map((x,i)=><button key={x} onClick={()=>{setSelected(x);dialog.current?.showModal()}} aria-label={`写真${i+1}を拡大`}><Photo name={x} alt={['トルテッリーニ','料理をつくる手','白樺の風景','デザート','生地に触れる手','冬の浅間山','手打ちパスタ','りんごのデザート'][i]}/></button>)}</section><dialog className="lightbox" ref={dialog} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}}><button className="close" autoFocus onClick={()=>dialog.current?.close()}>閉じる ×</button>{selected&&<img src={photo(selected)} alt="拡大した写真"/>}</dialog></>}
function App(){const route=()=>{const key=location.hash.replace('#/','')||'home';return ({cucina:'challenge',experience:'time',reserve:'visit',itabashi:'visit',nakayama:'karuizawa'} as Record<string,string>)[key]||key};const [page,setPage]=useState(route);const header=useScrollHeader(page);const menu=useRef<HTMLDialogElement>(null);useEffect(()=>{const go=()=>{setPage(route());menu.current?.close();window.scrollTo(0,0)};addEventListener('hashchange',go);return()=>removeEventListener('hashchange',go)},[]);useEffect(()=>{document.title=`${nav.find(n=>n[0]===page)?.[1]||'NAKAYAMA'} — 試作`;let frame=0;const update=()=>{frame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;document.documentElement.style.setProperty('--scroll',String(reduced?0:window.scrollY));document.querySelectorAll<HTMLElement>('.scene,.opening').forEach(el=>{const r=el.getBoundingClientRect();const p=Math.max(0,Math.min(1,-r.top/(el.offsetHeight-innerHeight)));el.style.setProperty('--progress',String(reduced?0:p))})};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);update();return()=>{removeEventListener('scroll',scroll);removeEventListener('resize',scroll);cancelAnimationFrame(frame)}},[page]);let content;switch(page){case'home':content=<Home/>;break;case'karuizawa':content=<NakayamaHome/>;break;case'questions':content=<Questions/>;break;case'challenge':content=<Challenge/>;break;case'time':content=<Time/>;break;case'people':content=<People/>;break;case'chef':content=<Chef/>;break;case'journal':content=<Journal/>;break;case'letter-hands':content=<Letter/>;break;case'letter-garden':content=<Letter garden/>;break;case'projects':content=<Projects/>;break;case'project-miyota':content=<Project/>;break;case'project-dialogue':content=<Project dialogue/>;break;case'course':content=<Course/>;break;case'visit':content=<Visit/>;break;case'landscape':content=<Gallery/>;break;default:content=<><Intro title="ページが見つかりません" en="NOT FOUND"/><Link to="home">ホームへ戻る</Link></>}
return <><a className="skip" href="#content" onClick={e=>{e.preventDefault();document.getElementById('content')?.focus()}}>本文へ</a><header ref={header} className="scroll-header"><a href="#/home" aria-label="ホーム"><img src={photo('arte-header.svg')} alt="arte LA CUCINA ITALIANA"/></a><div className="header-right"><button onClick={()=>menu.current?.showModal()} aria-label="メニューを開く">MENU <span>☰</span></button></div></header><dialog ref={menu} className="menu" onClick={e=>{if(e.target===e.currentTarget)menu.current?.close()}}><button className="close" autoFocus onClick={()=>menu.current?.close()}>閉じる ×</button><span className="eyebrow">NAKAYAMA</span><nav aria-label="サイトメニュー"><a href="#/home">ホーム</a>{nav.map(([key,label],i)=><a className={i===6?'nav-divider':''} key={key} href={href(key)} aria-current={page===key?'page':undefined}>{label}<span>↗</span></a>)}</nav></dialog><div className="particles" aria-hidden="true">{Array.from({length:24},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,top:`${(i*23)%100}%`,animationDelay:`-${(i*7)%29}s`,animationDuration:`${19+(i%5)*3}s`,width:`${2+(i%3)}px`,height:`${2+(i%3)}px`}}/>)}</div><main id="content" tabIndex={-1} key={page}>{content}</main>{page!=='home'&&<footer><img src={photo('arte-logo.svg')} alt="arte LA CUCINA ITALIANA"/><p>穏やかで特別なひとときをarteで</p><div><Link to="course">arteのメニュー</Link><Link to="visit">ご来店・予約</Link></div><a className="footer-instagram" href="https://www.instagram.com/arte_itabashiitalian/" target="_blank" rel="noopener noreferrer" aria-label="arteのInstagram（新しいタブで開く）" title="Instagram"><svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg></a><p className="editorial-link"><a href="#/questions">制作メモ：中山さんへの質問</a></p></footer>}</>}
export default App
